---
# tasks file for backend-build
- name: Add PHP Repo
  become: true
  apt_repository:
    repo: ppa:ondrej/php
    state: present

- name: Update dependencies
  become: true
  apt:
    update_cache: true

- name: Install PHP
  become: true
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - php8.1-common
    - php8.1-cli
    - php8.1-mbstring
    - php8.1-xml
    - unzip
    - php8.1-curl
    - php8.1-mysql
    - php8.1-fpm
    - php8.1-intl

- name: Add safe directory to git
  community.general.git_config:
    name: safe.directory
    value: /var/www/be-todo
    add_mode: add
    scope: global

- name: Clone BE Repo
  git:
    repo: https://github.com/elshiraphine/be-todo.git
    dest: /var/www/be-todo
    version: master
    force: true

- name: Change Permission
  file:
    path: /var/www/be-todo
    mode: '0777'
    recurse: true
  become: true

- name: Change Permission 2
  file:
    path: /usr/local/bin
    mode: '0777'
    recurse: true
  become: true

- name: Change index.php Permission
  file:
    path: /var/www/be-todo/public/index.php
    mode: '0666'
  become: true

- name: Change Ownership
  file:
    path: /var/www/be-todo
    group: www-data
    owner: www-data
    recurse: true
  become: true

- name: Download Composer Setup Script
  command: "php -r \"copy('https://getcomposer.org/installer', 'composer-setup.php');\""
  args:
    executable: /bin/bash

- name: Install Composer
  command: "php composer-setup.php --install-dir=/usr/bin --filename=composer"
  args:
    executable: /bin/bash

- name: Remove Composer Setup Script
  command: "php -r \"unlink('composer-setup.php');\""
  args:
    executable: /bin/bash

- name: Install Composer as root
  community.general.composer:
    command: install
    working_dir: /var/www/be-todo
    arguments: "--no-plugins --no-scripts"
  become: true
  become_user: root
  environment:
    COMPOSER_ALLOW_SUPERUSER: "1"

- name: Update Composer as root
  community.general.composer:
    command: update
    working_dir: /var/www/be-todo
    arguments: "--no-plugins --no-scripts"
  become: true
  become_user: root
  environment:
    COMPOSER_ALLOW_SUPERUSER: "1"