---

# - name: Backend Build
#   hosts: web_servers
#   become: true
#   roles:
#     - ../roles/backend-build

- name: Frontend Build
  hosts: web_servers
  become: true
  roles:
    - ../roles/frontend-build